version: '3'

services:

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/php-nginx/Dockerfile
    volumes:
      - ./api/storage:/app/storage
    ports:
      - "80:80"
    networks:
      - app-network

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./docker/nuxt/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
   
  db:
    image: 'mysql:8.0'
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    networks:
      - app-network
    volumes:
      - 'database:/var/lib/mysql'

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - 'redis:/var/lib/redis'

networks:
  app-network:
    driver: bridge

volumes:
  database:
    driver: local
  redis:
    driver: local