version: '3'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./api:/var/www/html/backend
    networks:
      - app-network

  webserver:
    container_name: webserver
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./api:/var/www/html/backend
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - app-network
    links:
      - frontend
    depends_on:
      - app
  db:
    image: 'mysql:8.0'
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: dev
      MYSQL_PASSWORD: secret
    networks:
      - app-network
    volumes:
      - 'database:/var/lib/mysql'

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./docker/nuxt/Dockerfile
    volumes:
      - ./frontend:/var/www/html/frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  database:
    driver: local
